languageCode: "en-us"
title: "Jonathan Campbell"
subtitle: "Jonathan Campbell's Blog -- Thoughts on Software Engineering & More"

baseURL: "https://jon.camp"
themesDir: "themes"
theme: "wizard"

params:
  contact:
    email: jon@healsdata.com
  author:
    name: Jonathan Campbell
  logo:
    standard: images/jc.png
    mobile: images/jc.png

copyright: This work is licensed under a Creative Commons Attribution 4.0 International license

publishDir: public
permalinks:
  /: /:slug/
  blog: /:sections[1:]/:slug/
  links: /links/:filename/

